# Generated by Django 4.1.4 on 2023-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_product_entrance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Entrance_Date',
            field=models.DateField(),
        ),
    ]
