# Generated by Django 4.1.4 on 2023-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_alter_product_entrance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Total_Price',
            field=models.FloatField(default=0),
        ),
    ]
