# Generated by Django 4.1.4 on 2023-10-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_product_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
