# Generated by Django 4.1.4 on 2023-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_solled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Approved_By',
            field=models.CharField(max_length=200),
        ),
    ]
