# Generated by Django 4.1.4 on 2023-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_alter_product_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Entrance_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Expired_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
