# Generated by Django 4.1.4 on 2023-10-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_delete_solled_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Deleted_Date', models.DateField(auto_now=True)),
                ('Deleted_By', models.CharField(max_length=200)),
                ('Total_Price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['Deleted_Date'],
            },
        ),
        migrations.CreateModel(
            name='Solled',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Solled_Date', models.DateField(auto_now=True)),
                ('Solled_By', models.CharField(max_length=200)),
                ('Total_Price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['Solled_Date'],
            },
        ),
    ]
