# Generated by Django 4.1.4 on 2023-11-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0010_profile_delete_user_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['Entrance_Date']},
        ),
        migrations.AlterModelTable(
            name='deletedproduct',
            table='deleted_products',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='solled',
            table='solled_products',
        ),
    ]
